spring:
  application:
    name: projeto-integrador
  datasource:
    url: jdbc:mysql://localhost/projeto-integrador
    username: root
    password: root123
  mvc:
    static-path-pattern: /static/**
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always